/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package trabalho_final;

/**
 *
 * @author User
 */
public class TelaBatalhaDois extends javax.swing.JPanel {

    /**
     * Creates new form TelaBatalhaDois
     */
    public TelaBatalhaDois() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        labelTituloUm = new javax.swing.JLabel();
        labelTituloDois = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHistoria = new javax.swing.JTextArea();
        buttonFugir = new javax.swing.JButton();
        progressVida = new javax.swing.JProgressBar();
        labelVida = new javax.swing.JLabel();
        labelMana = new javax.swing.JLabel();
        progressMana = new javax.swing.JProgressBar();
        buttonBatalhar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelFoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\BRUNNAPAGANINIBERTOL\\Documents\\aran.jpg")); // NOI18N

        labelTituloUm.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloUm.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTituloUm.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloUm.setText("The");

        labelTituloDois.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloDois.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTituloDois.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloDois.setText("Night");

        textHistoria.setBackground(new java.awt.Color(0, 0, 0));
        textHistoria.setColumns(20);
        textHistoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textHistoria.setForeground(new java.awt.Color(255, 255, 255));
        textHistoria.setRows(5);
        textHistoria.setText("Você encontrou o Guardião da Cripta!!\n                 O que deseja fazer?");
        jScrollPane1.setViewportView(textHistoria);

        buttonFugir.setBackground(new java.awt.Color(0, 0, 0));
        buttonFugir.setForeground(new java.awt.Color(204, 204, 0));
        buttonFugir.setText("Fugir");
        buttonFugir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        buttonFugir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFugirActionPerformed(evt);
            }
        });

        progressVida.setBackground(new java.awt.Color(102, 255, 102));
        progressVida.setToolTipText("");
        progressVida.setValue(100);

        labelVida.setBackground(new java.awt.Color(255, 255, 255));
        labelVida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVida.setForeground(new java.awt.Color(255, 255, 255));
        labelVida.setText("Vida");

        labelMana.setBackground(new java.awt.Color(255, 255, 255));
        labelMana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMana.setForeground(new java.awt.Color(255, 255, 255));
        labelMana.setText("Mana");

        progressMana.setBackground(new java.awt.Color(255, 51, 51));
        progressMana.setValue(100);

        buttonBatalhar.setBackground(new java.awt.Color(0, 0, 0));
        buttonBatalhar.setForeground(new java.awt.Color(204, 204, 0));
        buttonBatalhar.setText("Batalhar");
        buttonBatalhar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        buttonBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelVida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(progressVida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonFugir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelMana, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(progressMana, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonBatalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTituloUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTituloDois)
                        .addGap(0, 347, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelFoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloUm)
                    .addComponent(labelTituloDois, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVida)
                    .addComponent(progressVida, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressMana, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFugir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFugirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFugirActionPerformed
        new TelaJogar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonFugirActionPerformed

    private void buttonBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalharActionPerformed
        
    }//GEN-LAST:event_buttonBatalharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatalhar;
    private javax.swing.JButton buttonFugir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelMana;
    private javax.swing.JLabel labelTituloDois;
    private javax.swing.JLabel labelTituloUm;
    private javax.swing.JLabel labelVida;
    private javax.swing.JProgressBar progressMana;
    private javax.swing.JProgressBar progressVida;
    private javax.swing.JTextArea textHistoria;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
